Tech base lesson 16
grobovyi-oleksii/tech_base_rails pull request #19
Opened 2021-07-13 15:48 UTC by grobovyi-oleksii

Реализовать сортировку станций в маршруте так, как показано в скринкасте
Изменить добавление вагонов на вложенные ресурсы
Добавить время прибытия и отправления для каждой станции в маршруте
Сделать страницу поиска билетов на поезд:
       - Пользователь выбирает из списка начальную и конечную станцию. Выбирать можно из всех станций, которые есть в системе. Дату пока не указываем.
       - Система произвоидт поиск маршрутов по выбранному направлению и предоставляет пользователю список поездов, которые следуют по данному маршруту. При этом пользователь должен видеть время отправления от начальной станции и время прибытия на конечную
       - У пользователя должна быть возможность "купить" билет на поезд. Это должна быть кнопка "Купить" рядом с соответсвующим поездом. При нажатии на нее, запрашивается ФИО пассажира для билета (ведь пользователь может купить билет не для себя), данные паспорта и создается билет, связанный с пользователем и содержащий нужную информацию, после чего билет показывается пользователю (в произвольной форме).

2021-07-14 08:51 UTC, DmytroHavryshGoTo requested changes

2021-07-14 08:51 UTC, DmytroHavryshGoTo commented on app/controllers/searches_controller.rb
> +  def search
add checks for non-valid data. Bc here might be an error ActiveRecord::RecordNotFound

2021-07-14 08:51 UTC, DmytroHavryshGoTo commented on app/controllers/tickets_controller.rb
> +
empty line

2021-07-14 08:51 UTC, DmytroHavryshGoTo commented on app/controllers/tickets_controller.rb
> +    @ticket = Ticket.new
add checks for non-valid data. Bc here might be an error ActiveRecord::RecordNotFound

2021-07-14 08:51 UTC, DmytroHavryshGoTo commented on app/controllers/tickets_controller.rb
> +    @ticket.user = User.first
wtf, why User.first

2021-07-14 08:51 UTC, DmytroHavryshGoTo commented on app/controllers/tickets_controller.rb
> +    end
use guard clause

2021-07-14 08:51 UTC, DmytroHavryshGoTo commented on app/models/route.rb
> +  scope :with_station, ->(station) { Route.joins(:railway_stations).where('railway_stations.id = ?', station.id) }
why do you need `Route.joins`, you can use just `joins`

2021-07-14 08:51 UTC, DmytroHavryshGoTo commented on app/models/route.rb
> +    Route.with_station(start_station) & Route.with_station(end_station)
I think `Route` is unnecessary

2021-07-14 08:51 UTC, DmytroHavryshGoTo commented on app/models/train.rb
empty line

2021-07-14 08:51 UTC, DmytroHavryshGoTo commented on app/views/carriages/new.html.erb
> +    <%= form.submit "Создать" %>
Are you kidding me? Why it's in Russian? You have all other stuff in English.

2021-07-16 14:17 UTC, grobovyi-oleksii commented on app/controllers/tickets_controller.rb
> +    @ticket.user = User.first
Because authorization is not yet implemented in this version, and I thought that the hard code is a normal solution

2021-07-19 08:02 UTC, DmytroHavryshGoTo approved these changes
lgtm

2021-07-19 08:02 UTC, DmytroHavryshGoTo commented on app/controllers/searches_controller.rb
> +    unless RailwayStation.exists?(params[:start_station]) && RailwayStation.exists?(params[:end_station])
nice!

2021-07-19 08:04 UTC, merged